package design

import . "github.com/gobijan/gluey/dsl"

var _ = WebApp("todo", func() {
	Description("A simple todo list application")

	// Main todo resource
	Resource("todos", func() {
		// All RESTful actions are generated by default
		// GET    /todos          - List all todos
		// GET    /todos/new      - Show new todo form
		// POST   /todos          - Create new todo
		// GET    /todos/{id}     - Show single todo
		// GET    /todos/{id}/edit - Show edit form
		// PUT    /todos/{id}     - Update todo
		// DELETE /todos/{id}     - Delete todo

		Index(func() {
			Filterable("status", "priority")
		})
	})

	// Home page redirects to todos
	Page("home", "/")

	// Define the todo form
	Type("TodoForm", func() {
		Attribute("title", String, func() {
			Required()
			MinLength(1)
			MaxLength(200)
			Description("What needs to be done?")
		})
		Attribute("description", String, func() {
			MaxLength(1000)
			Description("Additional details (optional)")
		})
		Attribute("priority", String, func() {
			// Enum values would be validated at runtime
			Default("medium")
			Description("Priority: low, medium, or high")
		})
		Attribute("due_date", String, func() {
			Format(FormatDate)
			Description("When is it due?")
		})
		Attribute("completed", Boolean, func() {
			Description("Is it completed?")
		})
	})
})
