package codegen

import (
	"fmt"
	"strings"
)

// GenerateHeader creates the standard header for generated files.
// This header must be at the very top of the file (before package declaration)
// for IDEs and tools to properly recognize it as generated code.
func GenerateHeader(description, version, command string) string {
	var buf strings.Builder
	
	// Standard Go generated code marker - recognized by IDEs
	buf.WriteString(fmt.Sprintf("// Code generated by gluey v%s, DO NOT EDIT.\n", version))
	buf.WriteString("//\n")
	
	if description != "" {
		buf.WriteString(fmt.Sprintf("// %s\n", description))
		buf.WriteString("//\n")
	}
	
	if command != "" {
		buf.WriteString("// Command:\n")
		buf.WriteString(fmt.Sprintf("// $ %s\n", command))
		buf.WriteString("\n")
	}
	
	return buf.String()
}